### ISSUE TITLE
Update travis.yml to run tests, build, and deploy build artifacts

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/qccoders.org#49]
Add the following to `travis.yml`:

```yaml
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
```

Research heroku/travis integration to determine how to modify the pipeline to deploy the contents of the `/build/` folder instead of the root.

Note that webpack errors will begin to fail travis builds following this change.  Need volunteers to fix those errors before we can deploy.
